// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

/**
 * ice服务端
 **/
public interface _IServerOperationsNC
{
    /**
     * 服务端设置客户端回调对象
     **/
    boolean setCallBack(Ice.Identity id);

    /**
     * 服务端处理客户端请求
     **/
    boolean request(String msg);
}
