// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

/**
 * ice服务端
 **/
public interface _IServerOperations
{
    /**
     * 服务端设置客户端回调对象
     * @param __current The Current object for the invocation.
     **/
    boolean setCallBack(Ice.Identity id, Ice.Current __current);

    /**
     * 服务端处理客户端请求
     * @param __current The Current object for the invocation.
     **/
    boolean request(String msg, Ice.Current __current);
}
