// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

/**
 * ice客户端
 **/
public interface _IServerCallBackOperations
{
    /**
     * 客户端处理服务端返回
     * @param __current The Current object for the invocation.
     **/
    boolean response(String msg, Ice.Current __current);
}
