// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

public interface IServerPrx extends Ice.ObjectPrx {
    public boolean setCallBack(Ice.Identity id);

    public boolean setCallBack(Ice.Identity id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id, Ice.Callback __cb);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id, Callback_IServer_setCallBack __cb);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id, java.util.Map<String, String> __ctx, Callback_IServer_setCallBack __cb);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setCallBack(Ice.Identity id,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_BoolCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_setCallBack(Ice.AsyncResult __result);

    public boolean request(String msg);

    public boolean request(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_request(String msg);

    public Ice.AsyncResult begin_request(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_request(String msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_request(String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_request(String msg, Callback_IServer_request __cb);

    public Ice.AsyncResult begin_request(String msg, java.util.Map<String, String> __ctx, Callback_IServer_request __cb);

    public Ice.AsyncResult begin_request(String msg,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_request(String msg,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_request(String msg,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_request(String msg,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_BoolCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_request(Ice.AsyncResult __result);
}
