// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

public interface IServerCallBackPrx extends Ice.ObjectPrx {
    public boolean response(String msg);

    public boolean response(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_response(String msg);

    public Ice.AsyncResult begin_response(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_response(String msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_response(String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_response(String msg, Callback_IServerCallBack_response __cb);

    public Ice.AsyncResult begin_response(String msg, java.util.Map<String, String> __ctx, Callback_IServerCallBack_response __cb);

    public Ice.AsyncResult begin_response(String msg,
                                          IceInternal.Functional_BoolCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_response(String msg,
                                          IceInternal.Functional_BoolCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_response(String msg,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_BoolCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_response(String msg,
                                          java.util.Map<String, String> __ctx,
                                          IceInternal.Functional_BoolCallback __responseCb,
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                          IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_response(Ice.AsyncResult __result);
}
