// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

/**
 * ice客户端
 **/
public interface IServerCallBack extends Ice.Object,
        _IServerCallBackOperations, _IServerCallBackOperationsNC {
    public static final String ice_staticId = "::slice2java::IServerCallBack";

    public static final long serialVersionUID = -1151770L;
}
