// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

/**
 * ice服务端
 **/
public interface IServer extends Ice.Object,
        _IServerOperations, _IServerOperationsNC
{
    public static final String ice_staticId = "::slice2java::IServer";

    public static final long serialVersionUID = -457864017L;
}
