// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

public interface ISwitchCallbackPrx extends Ice.ObjectPrx
{
    public boolean sendMsg(String msg);

    public boolean sendMsg(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMsg(String msg);

    public Ice.AsyncResult begin_sendMsg(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMsg(String msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMsg(String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMsg(String msg, Callback_ISwitchCallback_sendMsg __cb);

    public Ice.AsyncResult begin_sendMsg(String msg, java.util.Map<String, String> __ctx, Callback_ISwitchCallback_sendMsg __cb);

    public Ice.AsyncResult begin_sendMsg(String msg, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMsg(String msg, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendMsg(String msg, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendMsg(String msg, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_BoolCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_sendMsg(Ice.AsyncResult __result);
}
