// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

/**
 * Provides type-specific helper functions.
 **/
public final class ISwitchPrxHelper extends Ice.ObjectPrxHelperBase implements ISwitchPrx
{
    private static final String __callBack_name = "callBack";

    public boolean callBack(String msg)
    {
        return callBack(msg, null, false);
    }

    public boolean callBack(String msg, java.util.Map<String, String> __ctx)
    {
        return callBack(msg, __ctx, true);
    }

    private boolean callBack(String msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__callBack_name);
        return end_callBack(begin_callBack(msg, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_callBack(String msg)
    {
        return begin_callBack(msg, null, false, false, null);
    }

    public Ice.AsyncResult begin_callBack(String msg, java.util.Map<String, String> __ctx)
    {
        return begin_callBack(msg, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_callBack(String msg, Ice.Callback __cb)
    {
        return begin_callBack(msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_callBack(String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_callBack(msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_callBack(String msg, Callback_ISwitch_callBack __cb)
    {
        return begin_callBack(msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_callBack(String msg, java.util.Map<String, String> __ctx, Callback_ISwitch_callBack __cb)
    {
        return begin_callBack(msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_callBack(String msg, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_callBack(msg, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_callBack(String msg, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_callBack(msg, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_callBack(String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_callBack(msg, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_callBack(String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_callBack(msg, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_callBack(String msg, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_callBack(msg, __ctx, __explicitCtx, __synchronous, 
                              new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                  {
                                      public final void __completed(Ice.AsyncResult __result)
                                      {
                                          ISwitchPrxHelper.__callBack_completed(this, __result);
                                      }
                                  });
    }

    private Ice.AsyncResult begin_callBack(String msg, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__callBack_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__callBack_name, __cb);
        try
        {
            __result.prepare(__callBack_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(msg);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_callBack(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __callBack_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __callBack_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        slice2java.ISwitchPrx __proxy = (slice2java.ISwitchPrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_callBack(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __heartbeat_name = "heartbeat";

    public boolean heartbeat(Ice.Identity id)
    {
        return heartbeat(id, null, false);
    }

    public boolean heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx)
    {
        return heartbeat(id, __ctx, true);
    }

    private boolean heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__heartbeat_name);
        return end_heartbeat(begin_heartbeat(id, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id)
    {
        return begin_heartbeat(id, null, false, false, null);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx)
    {
        return begin_heartbeat(id, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, Ice.Callback __cb)
    {
        return begin_heartbeat(id, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_heartbeat(id, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, Callback_ISwitch_heartbeat __cb)
    {
        return begin_heartbeat(id, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx, Callback_ISwitch_heartbeat __cb)
    {
        return begin_heartbeat(id, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_heartbeat(id, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_heartbeat(id, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_heartbeat(id, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_heartbeat(id, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.Functional_BoolCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_heartbeat(id, __ctx, __explicitCtx, __synchronous, 
                               new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                   {
                                       public final void __completed(Ice.AsyncResult __result)
                                       {
                                           ISwitchPrxHelper.__heartbeat_completed(this, __result);
                                       }
                                   });
    }

    private Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                            java.util.Map<String, String> __ctx, 
                                            boolean __explicitCtx, 
                                            boolean __synchronous, 
                                            IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__heartbeat_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__heartbeat_name, __cb);
        try
        {
            __result.prepare(__heartbeat_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            Ice.Identity.__write(__os, id);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_heartbeat(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __heartbeat_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __heartbeat_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        slice2java.ISwitchPrx __proxy = (slice2java.ISwitchPrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_heartbeat(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ISwitchPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), ISwitchPrx.class, ISwitchPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ISwitchPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), ISwitchPrx.class, ISwitchPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ISwitchPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), ISwitchPrx.class, ISwitchPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ISwitchPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), ISwitchPrx.class, ISwitchPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static ISwitchPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, ISwitchPrx.class, ISwitchPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static ISwitchPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, ISwitchPrx.class, ISwitchPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::slice2java::ISwitch"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, ISwitchPrx v)
    {
        __os.writeProxy(v);
    }

    public static ISwitchPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ISwitchPrxHelper result = new ISwitchPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
