// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

public interface ISwitchPrx extends Ice.ObjectPrx
{
    public boolean heartbeat(Ice.Identity id);

    public boolean heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, Ice.Callback __cb);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, Callback_ISwitch_heartbeat __cb);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, java.util.Map<String, String> __ctx, Callback_ISwitch_heartbeat __cb);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_heartbeat(Ice.Identity id, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_BoolCallback __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_heartbeat(Ice.AsyncResult __result);

    public boolean callBack(String msg);

    public boolean callBack(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_callBack(String msg);

    public Ice.AsyncResult begin_callBack(String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_callBack(String msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_callBack(String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_callBack(String msg, Callback_ISwitch_callBack __cb);

    public Ice.AsyncResult begin_callBack(String msg, java.util.Map<String, String> __ctx, Callback_ISwitch_callBack __cb);

    public Ice.AsyncResult begin_callBack(String msg, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_callBack(String msg, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_callBack(String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_callBack(String msg, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_BoolCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public boolean end_callBack(Ice.AsyncResult __result);
}
