// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `call.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

public interface ISwitchCallback extends Ice.Object,
                                         _ISwitchCallbackOperations, _ISwitchCallbackOperationsNC
{
    public static final String ice_staticId = "::slice2java::ISwitchCallback";

    public static final long serialVersionUID = 1996966641L;
}
