// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package slice2java;

public abstract class Callback_HelloI_hello
    extends IceInternal.TwowayCallback implements _Callback_HelloI_hello
{
    public final void __completed(Ice.AsyncResult __result)
    {
        HelloIPrxHelper.__hello_completed(this, __result);
    }
}
